# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agentclusterinstalls.extensions.hive.openshift.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: system
          name: assisted-service
          path: /convert
          port: 443
      conversionReviewVersions:
      - v1beta2
      - v1beta1
