// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TangConnectivityResponse tang connectivity response
//
// swagger:model tang_connectivity_response
type TangConnectivityResponse struct {

	// Tang check result.
	IsSuccess bool `json:"is_success,omitempty"`

	// tang servers
	TangServers []*TangServersResponse `json:"tang_servers"`
}

// Validate validates this tang connectivity response
func (m *TangConnectivityResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTangServers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TangConnectivityResponse) validateTangServers(formats strfmt.Registry) error {
	if swag.IsZero(m.TangServers) { // not required
		return nil
	}

	for i := 0; i < len(m.TangServers); i++ {
		if swag.IsZero(m.TangServers[i]) { // not required
			continue
		}

		if m.TangServers[i] != nil {
			if err := m.TangServers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tang_servers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("tang_servers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this tang connectivity response based on the context it is used
func (m *TangConnectivityResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTangServers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TangConnectivityResponse) contextValidateTangServers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.TangServers); i++ {

		if m.TangServers[i] != nil {
			if err := m.TangServers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tang_servers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("tang_servers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TangConnectivityResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TangConnectivityResponse) UnmarshalBinary(b []byte) error {
	var res TangConnectivityResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TangServersResponse tang servers response
//
// swagger:model TangServersResponse
type TangServersResponse struct {

	// Tang response payload.
	Payload string `json:"payload,omitempty"`

	// signatures
	Signatures []*TangSignatures `json:"signatures"`
}

// Validate validates this tang servers response
func (m *TangServersResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSignatures(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TangServersResponse) validateSignatures(formats strfmt.Registry) error {
	if swag.IsZero(m.Signatures) { // not required
		return nil
	}

	for i := 0; i < len(m.Signatures); i++ {
		if swag.IsZero(m.Signatures[i]) { // not required
			continue
		}

		if m.Signatures[i] != nil {
			if err := m.Signatures[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("signatures" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("signatures" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this tang servers response based on the context it is used
func (m *TangServersResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSignatures(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TangServersResponse) contextValidateSignatures(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Signatures); i++ {

		if m.Signatures[i] != nil {
			if err := m.Signatures[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("signatures" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("signatures" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TangServersResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TangServersResponse) UnmarshalBinary(b []byte) error {
	var res TangServersResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TangSignatures tang signatures
//
// swagger:model TangSignatures
type TangSignatures struct {

	// protected
	Protected string `json:"protected,omitempty"`

	// signature
	Signature string `json:"signature,omitempty"`
}

// Validate validates this tang signatures
func (m *TangSignatures) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tang signatures based on context it is used
func (m *TangSignatures) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TangSignatures) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TangSignatures) UnmarshalBinary(b []byte) error {
	var res TangSignatures
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
