// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TangConnectivityResponse tang connectivity response
//
// swagger:model tang_connectivity_response
type TangConnectivityResponse struct {

	// Tang check result.
	IsSuccess bool `json:"is_success,omitempty"`
}

// Validate validates this tang connectivity response
func (m *TangConnectivityResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tang connectivity response based on context it is used
func (m *TangConnectivityResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TangConnectivityResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TangConnectivityResponse) UnmarshalBinary(b []byte) error {
	var res TangConnectivityResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
